### ISSUE TITLE
A very small error

### ISSUE THREAD

**Issue by aierfulz** [btschwertfeger/python-cmethods#95]
core.py Line 148-149
 ```
   if kwargs.get("group", None) is None:
        return apply_ufunc(method, obs, simh, simp, **kwargs).to_dataset()

```
must be rename a dataarray object befor it be converted to dataset. so the L149 should be pass a name (for example, 'tas') and rewrite as `return apply_ufunc(method, obs, simh, simp, **kwargs).rename('tas').to_dataset()`.

**Comment by btschwertfeger** [comment]
@aierfulz, thank you for sharing your idea! Indeed I never thought about applying these techniques to xarray.Dataarrays that don't provide a name. For named dataarrays, the name provided by simp is taken - so no need to apply `rename`. 

To make this complete, here is an example of the error using the loaded data sets as shown in https://github.com/btschwertfeger/python-cmethods/blob/v2.2.2/examples/examples.ipynb:

```python
qdm_result = adjust(
    method = "quantile_delta_mapping",
    obs = obsh["tas"].rename(None),
    simh = simh["tas"].rename(None),
    simp = simp["tas"].rename(None),
    n_quantiles = 1000,
    kind = "+", 
)
```

... which will raise the following error: 
```error 
ValueError: unable to convert unnamed DataArray to a Dataset without providing an explicit name
```

IMO the error is very clear and could be avoided by adding a proper name to the input data sets. Extending the implementation as you suggested would add more complexity which is only needed in rare cases - and solved easier by adding a proper name. I don't see any actions to do here.

**Comment by aierfulz** [comment]
thank you for your detailed reply！😊
